{
 "title": "Speedtest",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Último resultado",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "Print" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "Download" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "Upload" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "Hora do teste" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Últimas 24h",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "PING",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 2 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "Ping" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "type": "dalvany-image-panel",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "URL" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "DOWNLOAD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "Download" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "UPLOAD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Casa" },
       "host": { "filter": "Teste de velocidade" },
       "item": { "filter": "Upload" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  }
 ]
}